/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_easyrpg_player_EasyRpgPlayerActivity */

#ifndef _Included_org_easyrpg_player_player_EasyRpgPlayerActivity
#define _Included_org_easyrpg_player_player_EasyRpgPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_CHANGE_TITLE
#define org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_CHANGE_TITLE 1L
#undef org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_UNUSED
#define org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_UNUSED 2L
#undef org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_TEXTEDIT_HIDE
#define org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_TEXTEDIT_HIDE 3L
#undef org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_USER
#define org_easyrpg_player_player_EasyRpgPlayerActivity_COMMAND_USER 32768L
/*
 * Class:     org_easyrpg_player_EasyRpgPlayerActivity
 * Method:    toggleFps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_easyrpg_player_player_EasyRpgPlayerActivity_toggleFps
  (JNIEnv *, jclass);

/*
 * Class:     org_easyrpg_player_EasyRpgPlayerActivity
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_easyrpg_player_player_EasyRpgPlayerActivity_endGame
  (JNIEnv *, jclass);

/*
 * Class:     org_easyrpg_player_EasyRpgPlayerActivity
 * Method:    setFastForwardMultiplier
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_easyrpg_player_player_EasyRpgPlayerActivity_setFastForwardMultiplier
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
