= easyrpg-player(6)
:manmanual: EasyRPG Manual
:mansource: EasyRPG Player {player_version}

== Name

easyrpg-player - Interpreter for RPG Maker 2000/2003 games


== Synopsis

*easyrpg-player* [<optional flags>...]


== Description

EasyRPG Player is an open source interpreter for RPG Maker 2000 and 2003 games.
It aims to support all features of unmodified games and also has some support
for some additional binary patches.

== Options

=== Engine options

*--autobattle-algo* _ALGO_::
  Which AutoBattle algorithm to use. Possible options:

  - 'RPG_RT'     - The default RPG_RT compatible algo, including RPG_RT bugs
  - 'RPG_RT+'    - The default RPG_RT compatible algo, with bug fixes
  - 'ATTACK'     - Like RPG_RT+, but only physical attacks, no skills

*-c*, *--config-path* _PATH_::
  Set a custom configuration path. When not specified, the configuration folder
  in the users home directory is used. The default configuration path is
  '$XDG_CONFIG_HOME/EasyRPG/Player'.

*--encoding* _ENCODING_::
  Instead of autodetecting the encoding or using the one in 'RPG_RT.ini', the
  specified encoding is used. 'ENCODING' is the number of the codepage used in
  Windows. Common encodings:
  - '932'  - Japanese (Shift-JIS)
  - '936'  - Simplified Chinese (GB2312)
  - '949'  - Korean (Unified Hangul)
  - '950'  - Traditional Chinese (Big5)
  - '1250' - Central European
  - '1251' - Cyrillic
  - '1252' - Western European (Latin 1)

NOTE: For games that only use ASCII (English games) use '1252'.

*--enemyai-algo* _ALGO_::
  Which EnemyAI algorithm to use. Possible options:
  - 'RPG_RT'      - The default RPG_RT compatible algo, including RPG_RT bugs
  - 'RPG_RT+'     - The default RPG_RT compatible algo, with bug fixes

*--engine* _ENGINE_::
  Disable autodetection of the simulated engine. Possible options:
   - 'rpg2k'       - RPG Maker 2000 (v1.00 - v1.10)
   - 'rpg2kv150'   - RPG Maker 2000 (v1.50 - v1.51)
   - 'rpg2ke'      - RPG Maker 2000 RPG Maker 2000 (English release, v1.61)
   - 'rpg2k3'      - RPG Maker 2003 (v1.00 - v1.04)
   - 'rpg2k3v105'  - RPG Maker 2003 (v1.05 - v1.09a)
   - 'rpg2k3e'     - RPG Maker 2003 RPG Maker 2003 (English release, v1.12)

*--language* _LANG_::
  Loads the game translation in language/'LANG' folder.

*--load-game-id* _ID_::
  Skip the title scene and load Save__ID__.lsd ('ID' is padded to two digits).

*--new-game*::
  Skip the title scene and start a new game directly.

*--no-log-color*::
  Disable colors in terminal log.

*--no-rtp*::
  Disable support for the Runtime Package (RTP). Will lead to checkerboard
  graphics and silent music/sound effects in games depending on the RTP.

*--patch* _PATCH_A_ [_PATCH_B_ _..._]::
  Instead of autodetecting patches used by this game, force emulation of certain
  patches.
   - 'common-this' - Support for __This Event__ in common events
   - 'dynrpg'      - DynRPG patch by Cherry
   - 'key-patch'   - Key Patch by Ineluki
   - 'maniac'      - Maniac Patch by BingShan
   - 'pic-unlock'  - Pictures are not blocked by messages
   - 'rpg2k3-cmds' - Support RPG Maker 2003 event commands in all engines

*--no-patch*::
  Disable all engine patches.

*--project-path* _PATH_::
  Instead of using the working directory, the game in 'PATH' is used.

*--record-input* _FILE_::
  Record all button inputs to 'FILE'.

*--replay-input* _FILE_::
  Replays button input from 'FILE', as generated by **--record-input**. If the
  RNG seed (**--seed**) and the state of the save file directory are the same as
  it was when the log was recorded, this should reproduce an identical run to
  the one recorded.

*--rtp-path* _PATH_::
  Adds 'PATH' to the RTP directory list and use this one with highest
  precedence.

*--save-path* _PATH_::
  Instead of storing save files in the game directory they are stored in
  'PATH'. The directory must exist.

NOTE: When using the game browser all games will share the same save
directory!

*--seed* _SEED_::
  Seeds the random number generator.


=== Video options

*--fps-limit*::
  In combination with *--no-vsync* sets a custom frames per second limit. If
  unspecified, the default is 60 fps. Set to 0 or use **--no-fps-limit** to
  disable the frame limiter. This option may not be supported on all platforms.

*--fps-render-window*::
  Render the frames per second counter in both fullscreen and windowed mode.
  Can be disabled with *--no-fps-render-window*.

*--fullscreen*::
  Start in fullscreen mode.

*--game-resolution* _RESOLUTION_::
  Force a different game resolution. RPG Maker games are designed for 320x240.
  This option fakes certain metrics to make games run at higher resolutions.
  Rendering in a different resolution can cause graphical glitches or break
  games entirely. Possible options:
   - 'original'    - 320x240 (4:3), the default resolution
   - 'widescreen'  - 416x240 (16:9)
   - 'ultrawide'   - 560x240 (21:9)

*--scaling* _MODE_::
  How the video output is scaled. Possible options:
   - 'nearest'    - Scale to screen size using nearest neighbour algorithm.
                    This is fast, but causes scaling artifacts.
   - 'integer'    - Like 'nearest' but scales to a multiple of the game
                    resolution to avoid artifacts.
   - 'bilinear'   - Like 'nearest' but apply a bilinear filter to avoid the
                    artifacts.
*--show-fps*::
  Enable display of the frames per second counter. Can be disabled with
  *--no-show-fps*.

*--stretch*::
  Ignore the aspect ratio and stretch video output to the entire width of the
  screen. Can be disabled with *--no-stretch*.

*--vsync*::
  Enables vertical sync. Vsync may or may not be supported on all platforms.
  Check the engine log to verify whether or not vsync actually is being used.
  Can be disabled with *--no-vsync*.

*--window*::
  Start in windowed mode.


=== Audio options

*--disable-audio*::
  Disable audio (in case you prefer your own music).

*--music-volume* _VOLUME_::
  Set the volume of background music to a value from 0 to 100.

*--sound-volume* _VOLUME_::
  Set the volume of sound effects to a value from 0 to 100.

*--soundfont* _FILE_::
  Adds 'FILE' to the list of soundfonts used for playing MIDI files and use
  this one with highest precedence. The soundfont must be in SF2 format.


=== Debug options

*--battle-test* _MONSTERPARTY_::
  Starts a battle test with the specified monster party. This is for starting
  battle tests in RPG Maker 2000.

*--battle-test* _MONSTERPARTY_ _FORMATION_ _CONDITION_ _TERRAIN_::
  Starts a battle test with the specified monster party, formation, start
  condition and terrain. This is for starting battle tests in RPG Maker 2003.

*--hide-title*::
  Hide the title background image and center the command menu.

*--start-map-id* _ID_::
  Overwrite the map used for new games and use Map__ID__.lmu instead ('ID' is
  padded to four digits).

NOTE: Incompatible with *--load-game-id*.

*--start-position* _X' 'Y_::
  Overwrite the party start position and move the party to position ('X', 'Y').

NOTE: Incompatible with *--load-game-id*.

*--start-party* _A_ [_B_ _..._]::
  Overwrite the starting party members with the actors with IDs 'A', 'B', '...'

NOTE: Incompatible with *--load-game-id*.

*--test-play*::
  Enable TestPlay (Debug) mode.


=== Other options

*-v*, *--version*::
  Display program version and exit.

*-h*, *--help*::
  Display help and exit.

For compatibility with the original RPG Maker runtime the following legacy
arguments are supported:

*BattleTest* _ID_::
  Same as *--battle-test*. The argument list starts at the 4th argument.

*HideTitle*::
  Same as *--hide-title*.

*TestPlay*::
  Same as *--test-play*.

*Window*::
  Same as *--window*.


== Environment

'RPG2K_RTP_PATH'::
  Full path to a directory containing an extracted RPG Maker 2000
  Runtime Package (RTP).

'RPG2K3_RTP_PATH'::
  Full path to a directory containing an extracted RPG Maker 2003 RTP.

'RPG_RTP_PATH'::
  Full path to a directory containing a combined RTP.

NOTE: All '*_RTP_PATH' variables support directory lists, using colon (':') or
semicolon (';') as separator. Useful when you have multiple translated RTP
versions or directories with extra files. The '--rtp-path' command line
option supports directory lists as well.

'SDL_SOUNDFONTS'::
  List of soundfonts in sf2 format to use when playing MIDI files. The first
  existing soundfont is used.

NOTE: Use colon (':') or semicolon (';') as separator. Use '--soundfont'
to specify a soundfont on the command line.


== Files

=== EasyRPG.ini
Sets game specific settings to alter the engine behaviour. It follows a simple
*Key*=_Value_ syntax in multiple sections.

Options in section 'Game':

*NewGame*=_1_::
  Same as *--new-game*.

*FakeResolution*=_1_::
  When 'WinW'/'WinH' in 'RPG_RT.ini' are used, enable the metric faking
  algorithm used by *--game-resolution*.

*Engine*=_ENGINE_::
  Same as *--engine*.

Options in section 'Patch' (see also *--patch*):

*CommonThisEvent*=_1_::
  Same as *--patch common-this*.

*DynRPG*=_1_::
  Same as *--patch dynrpg*.

*KeyPatch*=_1_::
  Same as *--patch key-patch*.

*Maniac*=_1_::
  Same as *--patch maniac*.

*PicUnlock*=_1_::
  Same as *--patch pic-unlock*.

*RPG2k3Commands*=_1_::
  Same as *--patch rpg2k3-commands*.

NOTE: Providing any patch option disables the patch autodetection of the engine.

Example:

----
[Game]
NewGame=1
Engine=rpg2k

[Patch]
CommonThisEvent=1
Maniac=1
----

NOTE: Values in the configuration file will overwrite auto detected ones,
however command line parameters will take precedence.

=== RPG_RT.ini
The game configuration file. It follows a simple *Key*=_Value_ syntax in
multiple sections.

Options in section 'RPG_RT':

*GameTitle*=_TITLE_::

  Title shown in the titlebar. The string must have the same encoding as the
  game (see also *--encoding*).

*FullPackageFlag*=_1_::

  Indicates that the game does not use assets from the Runtime Package (RTP).

*WinW*=_WIDTH_::

  Set a custom screen width in pixel. Use this in combination with *WinH*. The
  x and y coordinate are at the top-left corner. This behaviour can be
  altered with *FakeResolution*.

*WinH*=_HEIGHT_::

  Set a custom screen height.

NOTE: These resolution options invented by the Maniac Patch but they are
processed even when the patch is disabled. Using a custom resolution disables
*--game-resolution*.

Options in section 'EasyRPG':

*Encoding*=_ENCODING_::
  Same as *--encoding*.

Example:

----
[RPG_RT]
GameTitle=My Game
FullPackageFlag=1
WinW=640
WinH=480

[EasyRPG]
Encoding=1252
----

'Encoding=1252' sets the correct encoding for most english games.

NOTE: Values in the configuration file will overwrite auto detected ones,
however command line parameters will take precedence.

== Reporting Bugs

Bugs should be reported at the issue tracker:
https://github.com/EasyRPG/Player/issues


== Copyright / Authors

EasyRPG Player is Copyright (C) 2007-2023 the EasyRPG authors, see file
AUTHORS.md for details.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU GPL version 3.
See the file COPYING or http://gnu.org/licenses/gpl.html for details.


== See Also

mkxp - An open source RGSS (Ruby Game Scripting System) interface
implementation that aims to support games created by "RPG Maker XP",
"RPG Maker VX" and "RPG Maker VX Ace"

For additional information about EasyRPG software and related projects there
is a wiki: https://wiki.easyrpg.org
