/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_easyrpg_player_game_browser_GameScanner */

#ifndef _Included_org_easyrpg_player_game_browser_GameScanner
#define _Included_org_easyrpg_player_game_browser_GameScanner
#ifdef __cplusplus
extern "C" {
#endif

extern "C"
JNIEXPORT jobject JNICALL
Java_org_easyrpg_player_game_1browser_GameScanner_findGames(JNIEnv *env, jclass clazz, jstring path, jstring jmain_dir_name);

#ifdef __cplusplus
}
#endif
#endif
