/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_easyrpg_player_game_browser_GameScanner */

#ifndef _Included_org_easyrpg_player_game_browser_GameScanner
#define _Included_org_easyrpg_player_game_browser_GameScanner
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL
Java_org_easyrpg_player_game_1browser_GameScanner_decodeXYZfd(JNIEnv *env, jclass clazz, jint fd);

JNIEXPORT jbyteArray JNICALL
Java_org_easyrpg_player_game_1browser_GameScanner_decodeXYZbuffer(JNIEnv *env, jclass clazz,
																  jbyteArray buffer);

#ifdef __cplusplus
}
#endif
#endif
