/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_easyrpg_player_game_browser_GameScanner */

#ifndef _Included_org_easyrpg_player_game_browser_GameScanner
#define _Included_org_easyrpg_player_game_browser_GameScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_easyrpg_player_game_browser_GameScanner
 * Method:    decodeXYZ
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_easyrpg_player_game_1browser_GameScanner_decodeXYZ
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
