#!/bin/sh

echo $* |nkf -j|od -t d1 |sed \
 -e 's/.*27[ ]*36[ ]*66//' \
-e 's/27[ ]*40[ ].*//' | head -1 |awk '

{
    if ($1) {
	printf("%c%c: ", $1 + 128, $2 + 128);
	printf("%d  (%02x%02x)\n", $1*256 + $2, $1, $2);
    } else {
	printf("usage: kcode  漢字文字列(2文字まで)\n");
	exit 1;
    }

    if ($3) {
	printf("%c%c: ", $3 + 128, $4 + 128);
	printf("%d  (%02x%02x)\n", $3*256 + $4, $3, $4);
    }
}'