find_path(ICONV_INCLUDE_DIR iconv.h HINTS "/opt/local/include")
find_library(ICONV_LIBRARY iconv HINTS "/opt/local/lib")

if(EXISTS ${ICONV_INCLUDE_DIR})
  message(STATUS "iconv.h found: ${ICONV_INCLUDE_DIR}")
  set(Iconv_FOUND TRUE)

  if(NOT EXISTS ${ICONV_LIBRARY})
    set(ICONV_LIBRARY "")
  else()
    message(STATUS "iconv library found: ${ICONV_LIBRARY}")
  endif()
else()
  set(Iconv_FOUND FALSE)
endif()
