LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := smpeg2

EASYRPG_LIB_DIR = $(EASYDEV_ANDROID)/libs/armeabi-v7a

LOCAL_SRC_FILES := $(EASYRPG_LIB_DIR)/lib$(LOCAL_MODULE).so

include $(PREBUILT_SHARED_LIBRARY)
