LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := SDL2

EASYRPG_TOOLCHAIN_DIR = $(EASYDEV_ANDROID)/$(TARGET_ARCH_ABI)-toolchain

LOCAL_SRC_FILES := $(EASYRPG_TOOLCHAIN_DIR)/lib/lib$(LOCAL_MODULE).so

include $(PREBUILT_SHARED_LIBRARY)
