package org.easyrpg.player.settings;

enum SettingsEnum {
    VIBRATION_ENABLED("PREF_ENABLE_VIBRATION"),
    VIBRATE_WHEN_SLIDING_DIRECTION("PREF_VIBRATE_WHEN_SLIDING"),
    LAYOUT_TRANSPARENCY("PREF_LAYOUT_TRANSPARENCY"),
    IGNORE_LAYOUT_SIZE_SETTINGS("PREF_IGNORE_SIZE_SETTINGS"),
    LAYOUT_SIZE("PREF_SIZE_EVERY_BUTTONS"),
    EASYRPG_DIRECTORY("PREF_EASYRPG_DIRECTORIES"),
    RTP_DIRECTORY("PREF_RTP_DIRECTORIES"),
    FAVORITE_GAMES("PREF_FAVORITE_GAMES"),
    FORCED_LANDSCAPE("PREF_FORCED_LANDSCAPE"),
    FAST_FORWARD_MODE("FAST_FORWARD_MODE"),
    FAST_FORWARD_MULTIPLIER("FAST_FORWARD_MULTIPLIER");

    private final String label;

    SettingsEnum(String s) {
        this.label = s;
    }

    @Override
    public String toString() {
        return label;
    }
}
